### ISSUE TITLE
paraments setting

### ISSUE THREAD

**Issue by lucheng07082221** [afunTW/pytorch-mot-tracking#1]
Hi：

  I want to know how the paraments of kalman filter setting? thank you for your reply!

**Comment by afunTW** [comment]
@lucheng07082221

As soon as you understand the Kalman filter definition and your own data scenario, you would get the answer. In my case, it's two dimension tracking problem, and that's why the initial state looks like this.

Others parameter just a tuning process, let's try and error :)
